sudo: required
services:
  - docker

before_install:
  - docker build -t gregvinton/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run gregvinton/react-test npm test -- --coverage


after_success:
  - docker build -t gregvinton/multi-client .client/
  - docker build -t gregvinton/multi-nginx .nginx/
  - docker build -t gregvinton/multi-server .server/
  - docker build -t gregvinton/multi-worker ./worker 
#log in to the docker CLI
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
- docker push gregvinton/multi-client
- docker push gregvinton/multi-nginx 
- docker push gregvinton/multi-worker
- docker push gregvinton/multi-server
